run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - gosimple
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
